### ISSUE TITLE
Invalid move in Klondike solution due to ignoring card being face down

### ISSUE THREAD

**Issue by stpe** [thecharlesblake/Solvitaire#140]
The solver is making an invalid move because (seemingly) it ignores face up/down state of a card.

Note that fifth column, it got 3D face-up on top, while the 4C is technically face-down.

```
--- Foundations ---------
[]	4H	[]	[]	
--- Tableau Piles -------
KH	7C	8C	8S	4C*	QD	AS	
		7H	AD	3D*	JS	10C	
		6S	5H		9S	JC	
		5D	8D		QC	7D	
			7S		10H	6C	
			6H			JH	
			5S				
			4D				
--- Stock | Waste -------
5C	2D	
6D	KC	
8H	2S	
KS	10D	
4S	QH	
3S	2C	
JD		
QS		
9C		
3C		
KD		
9H		
10S		
9D		
AC
```

These two cards are now moved to column 3, ignoring that 3D must be moved first in order for 4C to be revealed.

```
--- Foundations ---------
[]	4H	[]	[]	
--- Tableau Piles -------
KH	7C	8C	8S	[]	QD	AS	
		7H	AD		JS	10C	
		6S	5H		9S	JC	
		5D	8D		QC	7D	
		4C*	7S		10H	6C	
		3D*	6H			JH	
			5S				
			4D				
--- Stock | Waste -------
5C	2D	
6D	KC	
8H	2S	
KS	10D	
4S	QH	
3S	2C	
JD		
QS		
9C		
3C		
KD		
9H		
10S		
9D		
AC
```

The starting deal attached as .json file:
[90PKF8L.json](https://github.com/thecharlieblake/Solvitaire/files/14237436/90PKF8L.json)

I see this using `--type klondike` as well as `--type klondike-deal-1`, also did rebuild using Docker image but no difference.

### Rules:
```
# ./solvitaire --describe-game-rules klondike-deal-1
The rules of 'klondike-deal-1' are as follows:
{
  "tableau piles": {
    "count": 7,
    "build policy": "red-black",
    "spaces policy": "kings",
    "move built group": "partial-if-card-above-buildable",
    "diagonal deal": true,
    "face up cards": "top"
  },
  "foundations": {
    "removable": true
  },
  "stock": {
    "size": 24,
    "deal count": 1,
    "redeal": true
  }
}
```

**Comment by turingfan** [comment]
Hi many thanks for letting us know about this. 

I agree this is an invalid move. I hoped that there had been some previous moves in the sequence which validated the move, e.g. the 3D having earlier moved and then moved back to the 4C (which is possible and can be necessary precisely to validate this.)  But when I ran it, the solution it gives has exactly this problem without the 3D having moved. 

This is very strange because we were definitely aware of this issue and I remembered us fixing this exact issue in an earlier version.  So it's disappointing to see it raise its head again.  

I will look into it.

**Comment by galcohensius** [comment]
It's been a while since I played with Solvitaire, but if I am not mistaken
the convention was that:

   - capital letters are face-up cards, and
   - lower-case letters are face-down cards.

So try to run this:


{
  "tableau piles": [
    [
      "7S"
    ],
    [
      "7c",
      "7H"
    ],
    [
      "8c",
      "4h",
      "6H"
    ],
    [
      "8s",
      "Ad",
      "5h",
      "8D"
    ],
    [
      "4c",
      "3d",
      "4d",
      "Ah",
      "KH"
    ],
    [
      "Qd",
      "Js",
      "9s",
      "Qc",
      "10h",
      "5S"
    ],
    [
      "As",
      "10c",
      "Jc",
      "7d",
      "6c",
      "Jh",
      "5D"
    ]
  ],
  "stock": [
    "5C",
    "6D",
    "8H",
    "KS",
    "4S",
    "3S",
    "JD",
    "QS",
    "9C",
    "3C",
    "KD",
    "9H",
    "10S",
    "9D",
    "AC",
    "3H",
    "2C",
    "QH",
    "10D",
    "2S",
    "KC",
    "6S",
    "2H",
    "2D"
  ]
}



Gal Cohensius
Algorithm Engineer
Beach Bum games <https://www.bbumgames.com/>

LinkedIn <https://www.linkedin.com/in/gal-cohensius-168332102/>
0528493215

**Comment by stpe** [comment]
Thank you, @galcohensius - now it does work as expected!

Then I would close this issue since it after all is not a bug (more part of the issue of general lack of documentation).

**Comment by turingfan** [comment]
Thanks both ... I wasn't aware of this representation either, as I only normally run random instances to compute percentages.  

Obviously agreed about the lack of documentation being an issue. 

Again many thanks  both
